---
title: "Analisis de RTT"
output:
  html_document:
    df_print: paged
---



```{r, echo =FALSE, results=FALSE, message=FALSE, warning=FALSE}

library ("mongolite")
library ("cowplot")
library("scales")
library("ggplot2")

#---- Functions ----

base_breaks <- function(n = 10){
  function(x) {
    axisTicks(log10(range(x, na.rm = TRUE)), log = TRUE, n = n)
  }
}

rtt_density <- function(rtt_list){
  # n: number of bins
  # bins: vector with rtt values representing bins limit
  # delta: diference between the values of each bin
  # h: standard histogram
  
  n=trunc(sqrt(length(rtt_list)))
  bins<-c(rtt_list[1])
  delta<-c()
  
  for (i in seq(n,length(rtt_list), by=n)){
    bins<-append(bins,rtt_list[i])
  }
  if (bins[length(bins)]!=rtt_list[length(rtt_list)]) {
    bins<-append(bins,rtt_list[length(rtt_list)])
  }
  for (i in seq(2,length(bins), by=1)){
    delta<-append(delta, bins[i]-bins[i-1] )
  }
  h <- hist(rtt_list, breaks = bins, plot=FALSE)
  h$counts=1/(sum(h$counts)*delta)
  rtt=data.frame(mids=h$mids, counts=h$counts)
  return(rtt)
}

get_mplsInfo <- function(ICMPExtensionsInfo, hopInfo){
  mpls_path <- ICMPExtensionsInfo
  mpls_info <- c()
  #print (length(hopInfo)) 
  for (i in 1: length(hopInfo)){
    #print(i)
    #print('mplspath')
    #print( mpls_path[[i]][[1]]$Info[3])
    if (is.null(mpls_path[[i]][[1]]$Info[3])) {
      mpls_info <- append (mpls_info,"< NoICMPExtensionMPLS >" )
    } else {
      mpls_info <- append (mpls_info, mpls_path[[i]][[1]]$Info[3])
    }
    #print('finish')
  }
  return(list(mpls_info))
}

get_mbModifications <- function (middleBoxInfo ){
  mb_path <- middleBoxInfo
  mb_info <- c()
  for (i in 1: length(mb_path)){
    mb_hop_info <- c()
    if (is.null(mb_path[[i]]) | length(mb_path[[i]]) == 0 ) {
      mb_info <- append (mb_info,"< NoMiddleBoxINfo >" )
    } else {
      for (j in 1:length(mb_path[[i]]) ){
        mb_hop_info <- append(mb_hop_info, colnames(mb_path[[i]][j]) )
        mb_hop_info <- append(mb_hop_info, ": <")
        mb_hop_info <- append(mb_hop_info, (mb_path[[i]][[j]][j,]$Expected) )
        mb_hop_info <- append(mb_hop_info, ",")
        mb_hop_info <- append(mb_hop_info, (mb_path[[i]][[j]][j,]$Received) )
        mb_hop_info <- append(mb_hop_info, ">")
      }
      mb_info <- append (mb_info, paste(mb_hop_info, collapse = ""))
    }
  }
  return(list(mb_info))  
}

get_pathStability <- function(paths){
  start <- c()
  finish <- c()
  changing_paths <- c()
  probe_ttl <- c()
  mpls_info <- c()
  mb_modifications <- c()
  mb_additions <- c()
  mb_deletions <- c()
  
  for (i in 1: nrow(paths$start)){
    #print ('i path')
    #print (i)
    if (i==1){
      start <- append(start,paths$start[['sec']][i])
      changing_paths <- append(changing_paths,list(paths$Hops[[i]]['from']$from))
      probe_ttl <-append(probe_ttl,list(paths$Hops[[i]]['hop']$hop))
      mpls_info <- append(mpls_info, get_mplsInfo(paths$Hops[[i]][['ICMPExtensions']],paths$Hops[[i]][['hop']]))
      
      mb_modifications <- append(mb_modifications, get_mbModifications(paths$Hops[[i]][['Modifications']])) 
      #mb_additions <- append(mb_additions, get_mbInfo(paths$Hops[[i]][['Additions']]))
      #mb_deletions <- append(mb_deletions, get_mbInfo(paths$Hops[[i]][['Deletions']]))
      
    } else if (!all(paths$Hops[[i]][['from']][2:length(paths$Hops[[i]][['hop']])] == paths$Hops[[i-1]][['from']][2:length(paths$Hops[[i-1]][['hop']])]) &&
               !all(get_mplsInfo(paths$Hops[[i]][['ICMPExtensions']],paths$Hops[[i]][['hop']][2:length(paths$Hops[[i]][['hop']])])[[1]] == get_mplsInfo(paths$Hops[[i-1]][['ICMPExtensions']], paths$Hops[[i-1]][['hop']][2:length(paths$Hops[[i-1]][['hop']])])[[1]])
    ){
      finish <- append(finish,paths$start[['sec']][i])
      start <- append(start,paths$start[['sec']][i])
      changing_paths <- append(changing_paths,list(paths$Hops[[i]]['from']$from))
      probe_ttl <-append(probe_ttl,list(paths$Hops[[i]]['hop']$hop))
      mpls_info <- append(mpls_info, get_mplsInfo(paths$Hops[[i]][['ICMPExtensions']],paths$Hops[[i]][['hop']]))
      mb_modifications <- append(mb_modifications, get_mbModifications(paths$Hops[[i]][['Modifications']])) 
      #mb_additions <- append(mb_additions, get_mbInfo(paths$Hops[[i]][['Additions']]))
      #mb_deletions <- append(mb_deletions, get_mbInfo(paths$Hops[[i]][['Deletions']]))
    }
    if (i == nrow(paths$start)){
      finish <- append(finish,paths$start[['sec']][i])
    }
  }
  
  #print (probe_ttl)
  #print (mpls_info)
  paths_stability_df <- data.frame(start)
  paths_stability_df$finish <- finish
  paths_stability_df$probe_ttl <- probe_ttl
  paths_stability_df$duration <- paths_stability_df$finish - paths_stability_df$start
  paths_stability_df$hops <- changing_paths
  paths_stability_df$mplsInfo <- mpls_info
  paths_stability_df$mbModifications <- mb_modifications
  #paths_stability_df$mbAdditions <- mb_additions
  #paths_stability_df$mbDeletions <- mb_deletions
  return(paths_stability_df)
}

plot_rtt <- function(RTT, probe_ttl, compare){
  rtt <-sapply(RTT$hops, unlist)
  rtt <- as.data.frame(t(rtt),stringsAsFactors = FALSE)
  #rtt <-  t(apply(rtt, 1, unlist))
  #rtt <-  as.data.frame(rtt,stringsAsFactors = FALSE)
  rtt$tx.sec <- as.numeric(rtt$tx.sec)
  rtt$rtt <- as.numeric(rtt$rtt)
  rtt$reply_ttl <- as.numeric(rtt$reply_ttl)
  rtt$probe_ttl <- as.numeric(rtt$probe_ttl )
  rtt$ftime <- as.POSIXlt(RTT$start$ftime) - 3600*3
  
  rtt <- subset (rtt, rtt <= quantile(rtt, .99))
  ip <- unique(rtt$addr)
  #rtt$hops.icmpext.mpls_labels.mpls_label <- as.numeric(rtt$hops.icmpext.mpls_labels.mpls_label )
  
  #subset
  #print('subset')
  
  if (compare){
      rtt1 <- subset(rtt, ftime <= as.POSIXlt("2018-05-03 03:59:56") )
      rtt2 <- subset(rtt, ftime > as.POSIXlt("2018-05-03 03:59:56") )
      
      p1 <- ggplot()+
      geom_line(data=rtt_density(sort(rtt1$rtt)) , aes(x=mids, y=counts), color="blue")+
      geom_line(data=rtt_density(sort(rtt2$rtt)) , aes(x=mids, y=counts), color="red")+
      scale_y_continuous(name = 'density', trans = log_trans(), breaks = base_breaks()) + 
      scale_x_continuous(name = 'rtt (s)', trans = log_trans(), breaks = base_breaks()) +
      theme_gray()+
      theme(axis.text.x = element_text(angle = 90))
      #ggtitle(paste0(ip,"\n probe ttl = ", probe_ttl)) 
      
      p2 <- ggplot()+
      geom_point(data= rtt1, aes(x=ftime, y=rtt), color="blue", alpha=0.3) +
      geom_point(data= rtt2, aes(x=ftime, y=rtt), color="red", alpha=0.3) + 
      scale_x_datetime()+
      scale_y_continuous(limits=c(min(rtt$rtt),quantile(rtt$rtt, .99)))+
      theme_gray()+
      labs( x = "time (s)", y = "rtt (s)")
      #ggtitle(paste0(ip,"\n probe ttl = ", probe_ttl)) 
    
  
      p3 <- ggplot()+
      geom_line(data= rtt1, aes(x=ftime, y=reply_ttl), color="blue") +
      geom_line(data= rtt2, aes(x=ftime, y=reply_ttl), color="red") + 
      scale_x_datetime()+
      theme_gray()+
      labs( x = "time (s)", y = "reply ttl")
      #ggtitle(paste0(ip,"\n probe ttl = ", probe_ttl)) 
      
      p4 <- ggplot()+
      geom_line(data= rtt1, aes(x=ftime, y=probe_ttl), color="blue") +
      geom_line(data= rtt2, aes(x=ftime, y=probe_ttl), color="red") + 
      scale_x_datetime()+
      theme_gray()+
      labs( x = "time (s)", y = "probe ttl")
      #ggtitle(paste0(ip,"\n probe ttl = ", probe_ttl)) 
      
  p<-plot_grid( p1, plot_grid( p2, p3, p4, nrow = 3, align = "v"), ncol = 2)
  title <- ggdraw() + draw_label(paste0(ip), fontface='bold')

  return(plot_grid(title, p, ncol=1, rel_heights=c(0.1, 1)))
  #return(plot_grid(p1, p2, ncol = 2))
    
  } else {
  
  p1 <- ggplot(data=rtt_density(sort(rtt$rtt)) , aes(x=mids, y=counts))+
        geom_line(color="gray")+
        scale_y_continuous(name = 'density', trans = log_trans(), breaks = base_breaks()) + 
        scale_x_continuous(name = 'rtt (ms)', trans = log_trans(), breaks = base_breaks()) +
        theme_gray()+
        theme(axis.text.x = element_text(angle = 90))
        #ggtitle(paste0(ip,"\n probe ttl = ", probe_ttl)) 
  
    p2 <- ggplot(data=rtt, aes(x=ftime, y=rtt))+
        geom_point(color="gray", alpha=0.3) +
        scale_x_datetime()+
        scale_y_continuous(limits=c(min(rtt$rtt),quantile(rtt$rtt, .99)))+
        theme_gray()+
        labs( x = "time (s)", y = "rtt (s)")
        #ggtitle(paste0(ip,"\n probe ttl = ", probe_ttl)) 
    
  
   p3 <- ggplot(data=rtt, aes(x=ftime , y=reply_ttl))+
        geom_line(color="red") +
        scale_x_datetime()+
        theme_gray()+
        labs(x = "time (s)", y = "reply ttl")
        #ggtitle(paste0(ip,"\n probe ttl = ", probe_ttl)) 
  
   
   p<-plot_grid( p1, plot_grid( p2, p3, nrow = 2, align = "v"), ncol = 2)
    title <- ggdraw() + draw_label(paste0(ip,"\n probe ttl = ", probe_ttl), fontface='bold')
  
  return(plot_grid(title, p, ncol=1, rel_heights=c(0.1, 1)))
  #return(plot_grid(p1, p2, ncol = 2))
    
}


  
  #p4 <- ggplot(data=rtt, aes(x=hops.tx.sec - min(hops.tx.sec) , y=hops.icmpext.mpls_labels.mpls_label))+
   #     geom_point(color="gray") +
    #    theme_gray()+
     #   labs(x = "time (s)", y = "reply ipid") 
    
    #labs(title = paste0('Addr: ' , unique(rtt$hops.addr), ' Hop: ' , probe_ttl),
    #     subtitle = paste0(ip_src , ' --> ',ip_dst ) , 
    #     x = "time (s)", y = "reply ttl")    
  

}
  

# ---- mongoDB connector: PATH  ----
pathCollection <-  mongo( collection = 'path',
                       db = 'conexdat',
                       url = 'mongodb://conexdat:1405871@ds163656.mlab.com:63656/conexdat'
)



# ---- mongoDB connector: RTT  ----
rttCollection <-  mongo( collection = 'rtt',
                       db = 'conexdat',
                       url = 'mongodb://conexdat:1405871@ds163656.mlab.com:63656/conexdat'
)
```

# Origen destino de la exploracion

Destinos disponibles:

```{r, echo =FALSE, message=FALSE, warning=FALSE}

# ---- mongoDB query: ALL IPsrc and IPdst List ----
query <- pathCollection$aggregate('[
                               { "$group" : { "_id" : {"src": "$src", "dst": "$dst"} } }
                               ]')

ip_src_dst <- query 

ip_src_dst[[1]]

ip_src <- '"192.168.0.126"'
ip_dst <- '"187.49.218.114"'
```
Destino actual:

* IP source: `r ip_src`
* IP destination: `r ip_dst`

# Paths descubiertos entre origen destino

```{r, echo =FALSE, results=FALSE, message=FALSE, warning=FALSE, rows.print=15}


# ---- mongoDB query: paths given a ip_src ip_dst ----
q <- paste('{ "src" : ', ip_src,', "dst" : ', ip_dst, '}')

f <- '{ "addr" : false,
        "name" : false,
        "max_hops": false,
        "Hops.delay": false,
        "Hops.Modifications.IP::CheckSum" : false,
        "Hops.Modifications.IP::TTL" : false,
        "Hops.ICMPExtensions.ICMPExtension": false,
        "Hops.ICMPExtensions.ICMPExtensionObject": false,
        "_id" : false}'

query <- pathCollection$find ( query = q, fields = f )
paths <- query

# ---- R algorithim: diferent paths analysis ----
pathStability <- get_pathStability(paths )

for (path in 1:length(pathStability)){
  print(pathStability[1:2, path])
  print(data.frame(c(probe_ttl= pathStability$probe_ttl[path], addr=pathStability$hops[path])))
  
}
```

```{r, echo =FALSE, results=FALSE, message=FALSE, warning=FALSE}
#probe_ttl <- 15
addr <- '"190.216.88.33"'
```

# probabilidad de densidad RTT para hop `r probe_ttl` e IP `addr` 

```{r, fig.width = 10, fig.height = 6 , echo =FALSE, results=FALSE, message=FALSE, warning=FALSE, }
q <- paste('{ "src" : ', ip_src, 
           ', "dst" : ', ip_dst,  
           #', "hops.probe_ttl" : ',  probe_ttl, 
           ', "hops.addr" : ',  addr,
           '}')
f <- '{ "hops.rtt" : true, "hops.tx.sec":true, "hops.probe_ttl" : true,  "hops.addr" : true , "hops.reply_ttl" : true , "start.ftime": true , "_id" : false}'
s <- '{"hops.rtt" : 1}'

query <- rttCollection$find ( query = q, fields = f)
rtt <- query
#print("rtt")
if(nrow(rtt) != 0){
  print(plot_rtt(rtt, probe_ttl, TRUE) )
}
```


